<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Begin Jekyll SEO tag v2.8.0 -->
<title>Handling errors | programming-25</title>
<meta name="generator" content="Jekyll v3.10.0" />
<meta property="og:title" content="Handling errors" />
<meta property="og:locale" content="en_US" />
<link rel="canonical" href="https://gapps123.github.io/programming-25/programming-25/data/data/part-6/3-errors.html" />
<meta property="og:url" content="https://gapps123.github.io/programming-25/programming-25/data/data/part-6/3-errors.html" />
<meta property="og:site_name" content="programming-25" />
<meta property="og:type" content="website" />
<meta name="twitter:card" content="summary" />
<meta property="twitter:title" content="Handling errors" />
<script type="application/ld+json">
{"@context":"https://schema.org","@type":"WebPage","headline":"Handling errors","url":"https://gapps123.github.io/programming-25/programming-25/data/data/part-6/3-errors.html"}</script>
<!-- End Jekyll SEO tag -->

    <link rel="stylesheet" href="/programming-25/data/assets/css/style.css?v=62b5e7c91b9857657f1df47190c60f9f584810ee">
    <!-- start custom head snippets, customize with your own _includes/head-custom.html file -->

<!-- Setup Google Analytics -->



<!-- You can set your favicon here -->
<!-- link rel="shortcut icon" type="image/x-icon" href="/programming-25/data/favicon.ico" -->

<!-- end custom head snippets -->

  </head>
  <body>
    <div class="container-lg px-3 my-5 markdown-body">
      
      <h1><a href="https://gapps123.github.io/programming-25/programming-25/data/">programming-25</a></h1>
      

      <text-box variant="learningObjectives" name="Learning objectives">

After this section

- You will know how to handle invalid input
- You will understand what are exceptions in programming
- You will be familiar with the most common exception types in Python
- You will be able to handle exceptions in your own programs

</text-box>

<p>The are two basic categories of errors that come up in programming contexts:</p>

<ol>
  <li>Syntax errors, which prevent the execution of the program</li>
  <li>Runtime errors, which halt the execution</li>
</ol>

<p>Errors in category 1 are usually easy to fix, as the Python interpreter flags the error location when attempting to execute the program. Common syntax errors include a missing colon at the end of a header line, or a missing quotation mark at the end of a string.</p>

<p>Errors in category 2 can be harder to spot, as it may happen that they only occur at a certain point in the execution of a program, and only in certain circumstances. The program may work just fine in most situations, but halt due to an error in a specific marginal case. We will now concentrate on handling these types of errors.</p>

<h2 id="input-validation">Input validation</h2>

<p>Many errors that come up during the execution of a program have to do with invalid input. Some examples include:</p>

<ul>
  <li>missing or empty input values in mandatory fields, such as empty strings when the length of the string is critical</li>
  <li>negative values where only positive values are accepted, such as -15 as the amount of an ingredient in a recipe</li>
  <li>missing files or typos in filenames</li>
  <li>values that are too small or too large, for example when working with dates and times</li>
  <li>invalid indexes, such as trying to access index 3 in the string “hey”</li>
  <li>values of a wrong type, such as strings when integers are expected</li>
</ul>

<p>Fortunately, we as programmers can prepare for most errors. Let’s have a look at a program which asks the user for their age, and makes sure it is an acceptable number (between 0 and 150, in this case):</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="n">age</span> <span class="o">=</span> <span class="nb">int</span><span class="p">(</span><span class="nb">input</span><span class="p">(</span><span class="s">"Please type in your age: "</span><span class="p">))</span>
<span class="k">if</span> <span class="n">age</span> <span class="o">&gt;=</span> <span class="mi">0</span> <span class="ow">and</span> <span class="n">age</span> <span class="o">&lt;=</span> <span class="mi">150</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s">"That is a fine age"</span><span class="p">)</span>
<span class="k">else</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s">"This is not a valid age"</span><span class="p">)</span>
</code></pre></div></div>

<sample-output>

Please type in your age: **25**
That is a fine age

</sample-output>

<sample-output>

Please type in your age: **-3**
This is not a valid age

</sample-output>

<p>As long as the user types in an integer value, our input validation seems to work fine. But what if they type in a string?</p>

<sample-output>

Please type in your age: **twenty-three**
ValueError: invalid literal for int() with base 10: 'twenty-three'

</sample-output>

<p>The <code class="language-plaintext highlighter-rouge">int</code> function is unable to parse the input string <code class="language-plaintext highlighter-rouge">twenty-three</code> as a valid integer value. The execution halts and the above error message is printed.</p>

<h2 id="exceptions">Exceptions</h2>

<p>Errors that occur while the program is already running are called <em>exceptions</em>. It is possible to prepare for exceptions, and handle them so that the execution continues despite them occurring.</p>

<p>Exception handling in Python is accomplished with <code class="language-plaintext highlighter-rouge">try</code> and <code class="language-plaintext highlighter-rouge">except</code> statements. The idea is that if something within a <code class="language-plaintext highlighter-rouge">try</code> block causes an exception, Python checks if there is a corresponding <code class="language-plaintext highlighter-rouge">except</code> block. If such a block exists, it is executed and the program themn continues as if nothing happened.</p>

<p>Let’s change the above example so that the program is prepared for the <code class="language-plaintext highlighter-rouge">ValueError</code> exception:</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">try</span><span class="p">:</span>
    <span class="n">age</span> <span class="o">=</span> <span class="nb">int</span><span class="p">(</span><span class="nb">input</span><span class="p">(</span><span class="s">"Please type in your age: "</span><span class="p">))</span>
<span class="k">except</span> <span class="nb">ValueError</span><span class="p">:</span>
    <span class="n">age</span> <span class="o">=</span> <span class="o">-</span><span class="mi">1</span>

<span class="k">if</span> <span class="n">age</span> <span class="o">&gt;=</span> <span class="mi">0</span> <span class="ow">and</span> <span class="n">age</span> <span class="o">&lt;=</span> <span class="mi">150</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s">"That is a fine age"</span><span class="p">)</span>
<span class="k">else</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s">"This is not a valid age"</span><span class="p">)</span>
</code></pre></div></div>

<sample-output>

Please type in your age: **twenty-three**
This is not a valid age

</sample-output>

<p>We can use the <code class="language-plaintext highlighter-rouge">try</code> block to flag that the code within the block may cause an error. In the <code class="language-plaintext highlighter-rouge">except</code> statement directly after the block the relevant error is mentioned. In the above example we covered only a <code class="language-plaintext highlighter-rouge">ValueError</code> exception. If the exception had some other cause, the execution would still have halted, despite the <code class="language-plaintext highlighter-rouge">try</code> and <code class="language-plaintext highlighter-rouge">except</code> blocks.</p>

<p>In the above example, if the error is caught, the value of <code class="language-plaintext highlighter-rouge">age</code> is set to -1. This is an invalid input value which we have already programmed behaviour for, as the program excpects the age of the user to be greater than 0.</p>

<p>In the following example we have a function <code class="language-plaintext highlighter-rouge">read_integer</code>, which asks the user to type in an integer value, but the function is also prepared for invalid input. The function keeps asking for integers until the user types in a valid input value.</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">def</span> <span class="nf">read_integer</span><span class="p">():</span>
    <span class="k">while</span> <span class="bp">True</span><span class="p">:</span>
        <span class="k">try</span><span class="p">:</span>
            <span class="n">input_str</span> <span class="o">=</span> <span class="nb">input</span><span class="p">(</span><span class="s">"Please type in an integer: "</span><span class="p">)</span>
            <span class="k">return</span> <span class="nb">int</span><span class="p">(</span><span class="n">input_str</span><span class="p">)</span>
        <span class="k">except</span> <span class="nb">ValueError</span><span class="p">:</span>
            <span class="k">print</span><span class="p">(</span><span class="s">"This input is invalid"</span><span class="p">)</span>

<span class="n">number</span> <span class="o">=</span> <span class="n">read_integer</span><span class="p">()</span>
<span class="k">print</span><span class="p">(</span><span class="s">"Thank you!"</span><span class="p">)</span>
<span class="k">print</span><span class="p">(</span><span class="n">number</span><span class="p">,</span> <span class="s">"to the power of three is"</span><span class="p">,</span> <span class="n">number</span><span class="o">**</span><span class="mi">3</span><span class="p">)</span>
</code></pre></div></div>

<sample-output>

Please type in an integer: **three**
This input is invalid
Please type in an integer: **aybabtu**
This input is invalid
Please type in an integer: **5**
Thank you!
5 to the power of three is 125

</sample-output>

<p>Sometimes it is enough to catch exceptions with a try-except structure, without doing anything about them. That is, we can just ignore the situation in the <code class="language-plaintext highlighter-rouge">except</code> block.</p>

<p>If we were to change the above example so that we only accepted integers smaller than 100, the results could look like this:</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">def</span> <span class="nf">read_small_integer</span><span class="p">():</span>
    <span class="k">while</span> <span class="bp">True</span><span class="p">:</span>
        <span class="k">try</span><span class="p">:</span>
            <span class="n">input_str</span> <span class="o">=</span> <span class="nb">input</span><span class="p">(</span><span class="s">"Please type in an integer: "</span><span class="p">)</span>
            <span class="n">number</span> <span class="o">=</span> <span class="nb">int</span><span class="p">(</span><span class="n">input_str</span><span class="p">)</span>
            <span class="k">if</span> <span class="n">number</span> <span class="o">&lt;</span> <span class="mi">100</span><span class="p">:</span>
                <span class="k">return</span> <span class="n">number</span>
        <span class="k">except</span> <span class="nb">ValueError</span><span class="p">:</span>
            <span class="k">pass</span> <span class="c1"># this command doesn't actually do anything
</span>
        <span class="k">print</span><span class="p">(</span><span class="s">"This input is invalid"</span><span class="p">)</span>

<span class="n">number</span> <span class="o">=</span> <span class="n">read_small_integer</span><span class="p">()</span>
<span class="k">print</span><span class="p">(</span><span class="n">number</span><span class="p">,</span> <span class="s">"to the power of three is"</span><span class="p">,</span> <span class="n">number</span><span class="o">**</span><span class="mi">3</span><span class="p">)</span>
</code></pre></div></div>

<sample-output>

Please type in an integer: **three**
This input is invalid
Please type in an integer: **1000**
This input is invalid
Please type in an integer: **5**
Thank you!
5 to the power of three is 125

</sample-output>

<p>Now the <code class="language-plaintext highlighter-rouge">except</code> block only contains the command <code class="language-plaintext highlighter-rouge">pass</code>, which doesn’t do anything. Python does not allow empty blocks, so the command is necessary.</p>

<programming-exercise name="Reading input" tmcname="part06-17_read_input">

Please write a function named `read_input`, which asks the user for input until the user types in an integer which falls within the bounds given as arguments to the function. The function should return the final valid integer value typed in by the user.

An example of the function in action:

```python
number = read_input("Please type in a number: ", 5, 10)
print("You typed in:", number)
```

<sample-output>

Please type in a number: **seven**
You must type in an integer between 5 and 10
Please type in a number: **-3**
You must type in an integer between 5 and 10
Please type in a number: **8**
You typed in: 8

</sample-output>

</programming-exercise>

<h2 id="typical-errors">Typical errors</h2>

<p>Here is a selection of typical errors you will likely come across, along with some situations where they may occur.</p>

<p><strong>ValueError</strong></p>

<p>This error is often thrown when the argument passed to a function is somehow invalid. For example, the function call <code class="language-plaintext highlighter-rouge">float("1,23")</code>causes an error, because decimals are always separated by a point in Python, and here we have a comma.</p>

<p><strong>TypeError</strong></p>

<p>This error occurs when a value is of the wrong type. For example, the function call <code class="language-plaintext highlighter-rouge">len(10)</code> causes a <code class="language-plaintext highlighter-rouge">TypeError</code>, because the function <code class="language-plaintext highlighter-rouge">len</code> requires a value whose length can be calculated, such as a string or a list.</p>

<p><strong>IndexError</strong></p>

<p>This common error occurs when trying to refer to an index which doesn’t exist. For example, the expression <code class="language-plaintext highlighter-rouge">"abc"[5]</code> causes an <code class="language-plaintext highlighter-rouge">IndexError</code>, because the string in question has no index 5.</p>

<p><strong>ZeroDivisionError</strong></p>

<p>As the name implies, this error is thrown when trying to divide by zero, which we know from mathematics to always be a bad idea. For example, if we try to determine the arithmetic mean of values in a list with the formula <code class="language-plaintext highlighter-rouge">sum(my_list) / len(my_list)</code>, but our list has length zero, this error will occur.</p>

<p><strong>Exceptions in file handling</strong></p>

<p>Some common errors when working with files are <strong>FileNotFoundError</strong> (when trying to access a file which doesn’t exist), <strong>io.UnsupportedOperation</strong> (when trying to perform an operation on a file which is not supported by the mode in which the file is opened) or <strong>PermissionError</strong> (the program lacks necessary permissions to access the file).</p>

<h2 id="handling-multiple-exceptions-at-once">Handling multiple exceptions at once</h2>

<p>There may be more than one <code class="language-plaintext highlighter-rouge">except</code> block attached to each <code class="language-plaintext highlighter-rouge">try</code> block. For example, the following program can handle both a <code class="language-plaintext highlighter-rouge">FileNotFoundException</code> and a <code class="language-plaintext highlighter-rouge">PermissionError</code>:</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">try</span><span class="p">:</span>
    <span class="k">with</span> <span class="nb">open</span><span class="p">(</span><span class="s">"example.txt"</span><span class="p">)</span> <span class="k">as</span> <span class="n">my_file</span><span class="p">:</span>
        <span class="k">for</span> <span class="n">line</span> <span class="ow">in</span> <span class="n">my_file</span><span class="p">:</span>
            <span class="k">print</span><span class="p">(</span><span class="n">line</span><span class="p">)</span>
<span class="k">except</span> <span class="nb">FileNotFoundError</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s">"The file example.txt was not found"</span><span class="p">)</span>
<span class="k">except</span> <span class="n">PermissionError</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s">"No permission to access the file example.txt"</span><span class="p">)</span>
</code></pre></div></div>

<p>Sometimes it is not necessary to specify the error the program prepares for. Especially when dealing with files, it is often enough to know that an error has occurred, and safely exit the program. It is not always necessary to know <em>why</em> the error occurred. If we need to cover for all possible exceptions, we can use the <code class="language-plaintext highlighter-rouge">except</code> block without specifying the error:</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code>
<span class="k">try</span><span class="p">:</span>
    <span class="k">with</span> <span class="nb">open</span><span class="p">(</span><span class="s">"example.txt"</span><span class="p">)</span> <span class="k">as</span> <span class="n">my_file</span><span class="p">:</span>
        <span class="k">for</span> <span class="n">line</span> <span class="ow">in</span> <span class="n">my_file</span><span class="p">:</span>
            <span class="k">print</span><span class="p">(</span><span class="n">line</span><span class="p">)</span>
<span class="k">except</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s">"There was an error when reading the file."</span><span class="p">)</span>

</code></pre></div></div>

<p>NB: the <code class="language-plaintext highlighter-rouge">except</code> statement here covers all possible errors, even those caused by the programming mistakes. Only syntax errors will not be caught by this, as they prevent the code from being executed in the first place.</p>

<p>For example, the following program will always throw an error, because the variable name <code class="language-plaintext highlighter-rouge">my_file</code> is written as <code class="language-plaintext highlighter-rouge">myfile</code> on the third line.</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">try</span><span class="p">:</span>
    <span class="k">with</span> <span class="nb">open</span><span class="p">(</span><span class="s">"example.txt"</span><span class="p">)</span> <span class="k">as</span> <span class="n">my_file</span><span class="p">:</span>
        <span class="k">for</span> <span class="n">line</span> <span class="ow">in</span> <span class="n">myfile</span><span class="p">:</span>
            <span class="k">print</span><span class="p">(</span><span class="n">line</span><span class="p">)</span>
<span class="k">except</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s">"There was an error when reading the file."</span><span class="p">)</span>
</code></pre></div></div>

<p>An <code class="language-plaintext highlighter-rouge">except</code> block can hide the actual error: the problem here was not caused by file handling as such, but by the variable name which was misspelled. Without the <code class="language-plaintext highlighter-rouge">except</code> block the error thrown would be shown, and the cause could be found more easily. Therefore it is usually a good idea to use only <code class="language-plaintext highlighter-rouge">except</code> blocks specifically declared for certain error types.</p>

<h2 id="passing-exceptions">Passing exceptions</h2>

<p>If executing a function causes an exception, and this exception is not handled, it is passed on to the section of code which called the function, and so forth up the call chain, until it reaches the main function level. If it is not handled there, either, the execution of the program halts, and the exception is usually printed out for the user to see.</p>

<p>In the following example we have the function <code class="language-plaintext highlighter-rouge">testing</code>. If it causes an exception, this is not handled within the function itself, but in the main function:</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">def</span> <span class="nf">testing</span><span class="p">(</span><span class="n">x</span><span class="p">):</span>
    <span class="k">print</span><span class="p">(</span><span class="nb">int</span><span class="p">(</span><span class="n">x</span><span class="p">)</span> <span class="o">+</span> <span class="mi">1</span><span class="p">)</span>

<span class="k">try</span><span class="p">:</span>
    <span class="n">number</span> <span class="o">=</span> <span class="nb">input</span><span class="p">(</span><span class="s">"Please type in a number: "</span><span class="p">)</span>
    <span class="n">testing</span><span class="p">(</span><span class="n">number</span><span class="p">)</span>
<span class="k">except</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s">"Something went wrong"</span><span class="p">)</span>
</code></pre></div></div>

<sample-output>

Please type in a number: **three**
Something went wrong

</sample-output>

<h2 id="raising-exceptions">Raising exceptions</h2>

<p>You can also raise exceptions, with the command <code class="language-plaintext highlighter-rouge">raise</code>. It may seem like an odd idea to purposefully cause errors in your programs, but it can, in fact, be a very useful mechanism.</p>

<p>For instance, it can sometimes be a good idea to raise an error when detecting invalid parameters. So far we have usually printed out messages when validating input, but if we are writing a function which is executed from elsewhere, just printing something out can go unnoticed when the function is called. Raising an error can make debugging easier.</p>

<p>In the following example we have a function which calculates factorials (for example, the factorial of the number 5 is 1 * 2 * 3 * 4 * 5). If the argument passed to the function is negative, the function raises an error:</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">def</span> <span class="nf">factorial</span><span class="p">(</span><span class="n">n</span><span class="p">):</span>
    <span class="k">if</span> <span class="n">n</span> <span class="o">&lt;</span> <span class="mi">0</span><span class="p">:</span>
        <span class="k">raise</span> <span class="nb">ValueError</span><span class="p">(</span><span class="s">"The input was negative: "</span> <span class="o">+</span> <span class="nb">str</span><span class="p">(</span><span class="n">n</span><span class="p">))</span>
    <span class="n">k</span> <span class="o">=</span> <span class="mi">1</span>
    <span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="mi">2</span><span class="p">,</span> <span class="n">n</span> <span class="o">+</span> <span class="mi">1</span><span class="p">):</span>
        <span class="n">k</span> <span class="o">*=</span> <span class="n">i</span>
    <span class="k">return</span> <span class="n">k</span>

<span class="k">print</span><span class="p">(</span><span class="n">factorial</span><span class="p">(</span><span class="mi">3</span><span class="p">))</span>
<span class="k">print</span><span class="p">(</span><span class="n">factorial</span><span class="p">(</span><span class="mi">6</span><span class="p">))</span>
<span class="k">print</span><span class="p">(</span><span class="n">factorial</span><span class="p">(</span><span class="o">-</span><span class="mi">1</span><span class="p">))</span>
</code></pre></div></div>

<sample-output>

6
720
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    print(factorial(-1))
  File "test.py", line 3, in factorial
    raise ValueError("The input was negative: " + str(n))
ValueError: The input was negative: -1

&lt;/sample-output&gt;


<programming-exercise name="Parameter validation" tmcname="part06-18_parameter_validation">

Please write a function named `new_person(name: str, age: int)`, which creates and returns a tuple containing the data in the arguments. The first element should be the name and the second the age.

If the values stored in the parameter variables are not valid, the function should throw a `ValueError` exception.

Invalid parameters in this case include:

* name is an empty string
* name contains less than two words
* name is longer than 40 characters
* age is a negative number
* age is greater than 150

</programming-exercise>

<programming-exercise name="Incorrect lottery numbers" tmcname="part06-19_incorrect_lottery_numbers">

The file `lottery_numbers.csv` containts winning lottery numbers in the following format:

<sample-data>

week 1;5,7,11,13,23,24,30
week 2;9,13,14,24,34,35,37
...etc...

</sample-data>

Each line should contain a header `week x`, followed by seven integer numbers which are all between 1 and 39 inclusive.

The file has been corrupted. Lines in the file may contain the following kinds of errors (these exact lines may not be present in the file, but errors in a similar format will be):

The week number is incorrect:

<sample-data>

week zzc;1,5,13,22,24,25,26

</sample-data>

One or more numbers are not correct:

<sample-data>

week 22;1,**,5,6,13,2b,34

</sample-data>

Too few numbers:

<sample-data>

week 13;4,6,17,19,24,33

</sample-data>

The numbers are too small or large:

<sample-data>

week 39;5,9,15,35,39,41,105

</sample-data>

The same number appears twice:

<sample-data>

week 41;5,12,3,35,12,14,36

</sample-data>

Please write a function named `filter_incorrect()`, which creates a file called `correct_numbers.csv`. The file should contain only those lines from the original file which are in the correct format.

</programming-exercise>

<!---
A quiz to review the contents of this section:

<quiz id="69694e01-4c47-5b9d-8a00-b0d96a477dc7"></quiz>
-->
</module></sample-output>


      
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/anchor-js/4.1.0/anchor.min.js" integrity="sha256-lZaRhKri35AyJSypXXs4o6OPFTbTmUoltBbDCbdzegg=" crossorigin="anonymous"></script>
    <script>anchors.add();</script>
  </body>
</html>
